# Generated by Django 5.2.1 on 2025-12-27 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_notification_options_alter_notification_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.JSONField(default='no rule found', help_text='List of rules for the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddIndex(
            model_name='eventteammember',
            index=models.Index(fields=['email'], name='events_even_email_08e3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventteammember',
            index=models.Index(fields=['status'], name='events_even_status_74276a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventteammember',
            index=models.Index(fields=['team'], name='events_even_team_id_f7f916_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='events_noti_user_id_bdde29_idx'),
        ),
    ]
