# Generated by Django 5.2.1 on 2026-01-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image_event_rules_alter_event_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=models.JSONField(default=['no rule found'], help_text='List of rules for the event'),
        ),
    ]
