# Generated by Django 5.2.1 on 2026-01-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventcustomfield_eventsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
