# Generated by Django 5.2.1 on 2026-01-27 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventsubmission_is_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfoField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('description', 'Long Description'), ('json', 'JSON'), ('url', 'URL')], max_length=20)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('value_url', models.URLField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_fields', to='events.event')),
            ],
        ),
    ]
