# Generated by Django 5.2.1 on 2026-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_image_url_alter_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
