# Generated by Django 5.2.1 on 2026-01-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='uuid',
        ),
    ]
