# Generated by Django 5.2.1 on 2025-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailotp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college_name',
            field=models.CharField(default='unknown college', max_length=255),
        ),
    ]
